version: '3.7'
services:
  database:
    image: 'postgres:13.2'
    ports:
      - 10081:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lrngapp
      - POSTGRES_PASSWORD=lrngapp

volumes:
  database-data:
